config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join('|')}/ do
    devise_for :users
    # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
    # Defines the root path route ("/")
    root to: 'posts#index'

    resources :user_posts, only: %i[index new create update destroy edit]
    resources :post_likes, only: %i[create]
    get 'profiles/:username', to: 'profiles#index', as: :profile
    resources :subscriptions, only: %i[create destroy]
    resources :feeds, only: %i[index]
    resources :posts do
      resources :comments
    end
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_user, only: %i[index]

  def index
    redirect_to user_posts_path if @user.username == current_user.username

    if @user
      @posts = Post.where(user_id: @user.id)
    else
      redirect_to root_path, notice: t('.error_find_user')
    end
  end

  private

  def set_user
    @user = User.find_by(username: params[:username])
  end
end

app/views/profiles/index.html.erb
<div class="col-lg-7">
  <div class="row justify-content-center align-items-center">
    <H2 class = "mr-3">Пользователь <%= params[:username] %></H2>
    <% if current_user.following?(@user) %>
      <%= button_to "Отписаться", subscription_path(@user), method: :delete, class: "btn btn-danger" %>
    <% else %>
      <%= button_to "Подписаться", subscriptions_path(id: @user.id), method: :post, class: "btn btn-primary" %>
    <% end %>
  </div>
  <div class="row justify-content-center align-items-center border-bottom mb-5">
    <div class="col-lg-2">публикаций</div>
    <div class="col-lg-2"><%= @user.followers.count %> подписчиков</div>
    <div class="col-lg-2"><%= @user.following.count %> подписок</div>
  </div>
  <!--ТУТ НАЧИНАЕТСЯ ВЫВОД ПОСТА С КАРУСЕЛЯМИ-->
  <div class="row">
    <div class="col-lg-2"></div>
    <div class="col-lg-7">
      <% @posts.each do |post| %>
        <% if post.images.attached? %>
          <div id="carouselExampleControls<%= post.id %>" class="carousel slide" data-interval="false" data-ride="carousel" style="background-color: rgba(169, 169, 169, 0.5);">
            <div class="carousel-inner">
              <% post.images.each_with_index do |image, index|  %>
                <% if index == 0 %>
                  <div class="carousel-item active">
                    <%= image_tag image, class: 'd-block w-30' %>
                  </div>
                <% else %>
                  <div class="carousel-item">
                    <%= image_tag image, class: 'd-block w-30' %>
                  </div>
                <% end %>
              <% end %>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleControls<%= post.id %>" role="button" data-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleControls<%= post.id %>" role="button" data-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            </a>
          </div>
          <div class="row mt-2 border-bottom">
            <div class="col-lg-2">
              <%= button_to "Like", post_likes_path(post.id), method: :post %>
            </div>
            <div class="col-lg-7 text-center">
              <p><%=post.likes_count%> отметок "нравится" </p>
            </div>
            <div class="col-lg-3">
              <p>Автор: <%= post.user.username %> </p>
            </div>
          </div>
          <div class="row">
            <div class="col-lg-12 border-bottom text-center">
              <h6>текст поста:<br>
                <%= post.body %> </h6>
              <p>дата создания:   <%=post[:created_at].strftime('%F %H:%M')%></p>
              <%if post.created_at.to_i != post.updated_at.to_i%>
                <p>изменено: <%=post[:updated_at].strftime('%F %H:%M')%></p>
              <%end%>
            </div>
          </div>
          <div class="row text-center">
            <div class="col-lg-12">
              <p>Комментарии:</p>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
  <!--ТУТ Заканчивается-->
</div>