config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join('|')}/ do
    devise_for :users
    # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
    # Defines the root path route ("/")
    root to: 'posts#index'

    resources :user_posts, only: %i[index new create update destroy edit]
    resources :post_likes, only: %i[create]
    get 'profiles/:username', to: 'profiles#index', as: :profile
    resources :subscriptions, only: %i[create destroy]
    resources :feeds, only: %i[index]
    resources :posts do
      resources :comments
    end
  end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  def index
    @posts = Post.where(user_id: current_user.following.pluck(:id))
  end
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/views/feeds/index.html.erb
<div class="col-lg-7">
  <div class="row justify-content-center align-items-center border-bottom mb-5">
    <H1> <%= t('.title') %> </H1>
  </div>
  <!--ТУТ НАЧИНАЕТСЯ ВЫВОД ПОСТА С КАРУСЕЛЯМИ-->
  <div class="row">
    <div class="col-lg-2"></div>
    <div class="col-lg-7">
      <% @posts.each do |post| %>
        <% if post.images.attached? %>
          <div id="carouselExampleControls<%= post.id %>" class="carousel slide" data-interval="false" data-ride="carousel" style="background-color: rgba(169, 169, 169, 0.5);">
            <div class="carousel-inner">
              <% post.images.each_with_index do |image, index| %>
                <% if index == 0 %>
                  <div class="carousel-item active">
                    <%= image_tag image, class: 'd-block w-30' %>
                  </div>
                <% else %>
                  <div class="carousel-item">
                    <%= image_tag image, class: 'd-block w-30' %>
                  </div>
                <% end %>
              <% end %>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleControls<%= post.id %>" role="button" data-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleControls<%= post.id %>" role="button" data-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            </a>
          </div>
          <div class="row mt-2 border-bottom">
            <div class="col-lg-2">
              <% has_like = post.likes.find { |like| like.user_id == current_user.id} %>
              <% if has_like %>
                <%= button_to t('.unlike'), post_likes_path(post_id: post.id), method: :post %>
              <% else %>
                <%= button_to t('.like'), post_likes_path(post_id: post.id), method: :post %>
              <% end %>
            </div>
            <div class="col-lg-7 text-center">
              <p><%= post.likes_count %> <%= t('.likes_count') %>  </p>
            </div>
            <div class="col-lg-3">
              <p> <%= link_to "#{h(t('.user_path'))} : #{h(post.user.username)}", profile_path(post.user.username) %> </p>
            </div>
          </div>
          <div class="row">
            <div class="col-lg-12 border-bottom text-center">
              <h6>
                <%= post.body %> </h6>
              <% if post.created_at.to_i != post.updated_at.to_i %>
                <p><%= t('.updated_at') %>: <%= post[:updated_at].strftime('%F %H:%M') %></p>
              <% else %>
                <p><%= t('.created_at') %>: <%= post[:created_at].strftime('%F %H:%M') %></p>
              <% end %>
            </div>
          </div>
          <h6><%= t('.comments') %>: </h6>
          <aside>
            <div id="comments-<%= post.id %>">
              <% post.comments.each do |comment| %>
                <%= render 'comments/comment', comment: comment %>
              <% end %>
            </div>
            <%= render 'comments/form', post: post %>
          </aside>
        <% end %>
      <% end %>
    </div>
  </div>
</div>
<!--ТУТ Заканчивается-->
</div>