config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join('|')}/ do
    devise_for :users
    # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
    # Defines the root path route ("/")
    root to: 'posts#index'

    resources :user_posts, only: %i[index new create update destroy edit]
    resources :post_likes, only: %i[create]
    get 'profiles/:username', to: 'profiles#index', as: :profile
    resources :subscriptions, only: %i[create destroy]
    resources :feeds, only: %i[index]
    resources :posts do
      resources :comments
    end
  end
end

app/controllers/user_posts_controller.rb
# frozen_string_literal: true

class UserPostsController < ApplicationController
  before_action :post_params, only: %i[create]
  before_action :set_current_user, only: %i[index]
  before_action :set_post, only: %i[edit update destroy]
  before_action :authorize_user_post!, only: %i[edit update destroy]
  after_action :verify_authorized, only: %i[edit update destroy]

  def index
    @posts = Post.where(user_id: current_user.id)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to root_path, notice: t('.success_post')
    else
      redirect_to root_path, notice: t('.error_post')
    end
  end

  def update
    if @post.update(post_params)
      attachments = ActiveStorage::Attachment.where(id: params[:deleted_img_ids])
      attachments.each(&:purge)

      redirect_to user_posts_path, notice: t('.success_update_post')
    else
      redirect_to user_posts_path, notice: t('.error_update_post')
    end
  end

  def edit; end

  def destroy
    if @post.destroy
      redirect_to user_posts_path, notice: t('.success_destroy_post')
    else
      redirect_to user_posts_path, notice: t('.error_destroy_post')
    end
  end

  private

  def authorize_user_post!
    authorize(@post || Post, policy_class: UserPostPolicy)
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def set_current_user
    @user = User.find_by(id: current_user.id)
  end

  def post_params
    params.require(:post).permit(:body, images: []).merge(user_id: current_user.id)
  end
end

app/helpers/user_posts_helper.rb
module UserPostsHelper
end

app/views/user_posts/edit.html.erb
<div class="col-lg-8">
  <div class="container">
    <div class="row justify-content-center align-items-center" style="height: 100vh;">
      <div class="col-lg-12">
        <%= form_with(model: @post, url: user_post_path(@post), html: { class: "justify-content-center" }) do |form| %>
          <% @post.images.each do |p| %>
            <h4><%= t('.select_photos') %>: </h4>
            <div class="box_image">
              <div class="box_content">
                <%= image_tag p.variant(resize_to_limit: [400, 400]) %>
                <%= check_box_tag "deleted_img_ids[]", p.id %>
              </div>
            </div>
          <% end %>
          <div class="form-group">
            <%= form.label :body, t('.description_label') %>
            <%= form.text_area :body, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= form.submit controller.action_name = t('.edit'), class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/user_posts/index.html.erb
<div class="col-lg-7">
  <div class="row justify-content-center align-items-center">
    <H1 class = "mr-3"><%= t('.my_profile') %></H1>
  </div>
  <div class="row justify-content-center align-items-center border-bottom mb-5">
    <div class="col-lg-2"> <%= t('.publications') %>: <%= @user.posts.count %></div>
    <div class="col-lg-2"> <%= t('.followers')%>: <%= @user.followers.count %></div>
    <div class="col-lg-2"> <%= t('.following')%>: <%= @user.following.count %></div>
  </div>
  <% if @posts.empty? %>
    <H1><%= t('.no_have_post') %> </H1>
    <%= button_to t('.create_button'), new_user_post_path, method: :get %>
  <% end %>
  <!--ТУТ НАЧИНАЕТСЯ ВЫВОД ПОСТА С КАРУСЕЛЯМИ-->
  <div class="row">
    <div class="col-lg-2"></div>
    <div class="col-lg-7">
      <% @posts.each do |post| %>
        <% if post.images.attached? %>
          <div id="carouselExampleControls<%= post.id %>" class="carousel slide" data-interval="false" data-ride="carousel" style="background-color: rgba(169, 169, 169, 0.5);">
            <div class="carousel-inner">
              <% post.images.each_with_index do |image, index|  %>
                <% if index == 0 %>
                  <div class="carousel-item active">
                    <%= image_tag image, class: 'd-block w-30' %>
                  </div>
                <% else %>
                  <div class="carousel-item">
                    <%= image_tag image, class: 'd-block w-30' %>
                  </div>
                <% end %>
              <% end %>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleControls<%= post.id %>" role="button" data-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleControls<%= post.id %>" role="button" data-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            </a>
          </div>
          <hr>
          <p><%= post.body %> </p>
        <% end %>
        <div class="row mb-5">
          <div class="btn-group" role="group" aria-label="Basic example">
            <%= button_to t('.edit'), edit_user_post_path(post.id), class: "btn btn-secondary mr-2", method: :get %>
            <%= button_to t('.delete'), user_post_path(post.id), class: "btn btn-secondary", method: :delete, onclick: "return confirm('#{t('.confirm_delete_post')}')" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/user_posts/new.html.erb
<div class="col-lg-8">
  <div class="container">
    <div class="row justify-content-center align-items-center" style="height: 100vh;">
      <div class="col-lg-4">
        <%= form_with(model: @post, url: user_posts_path, html: { class: "justify-content-center" }) do |form| %>
          <div class="form-group">
            <%= form.label t('.add_photos') %>
            <%= form.file_field :images, multiple: true,  class: "form-control", value: "test" %>
          </div>
          <div class="form-group">
            <%= form.label t('.add_description') %>
            <%= form.text_area :body, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= form.submit controller.action_name = t('.create_button'), class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>