config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join('|')}/ do
    devise_for :users
    # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
    # Defines the root path route ("/")
    root to: 'posts#index'

    resources :user_posts, only: %i[index new create update destroy edit]
    resources :post_likes, only: %i[create]
    get 'profiles/:username', to: 'profiles#index', as: :profile
    resources :subscriptions, only: %i[create destroy]
    resources :feeds, only: %i[index]
    resources :posts do
      resources :comments
    end
  end
end

app/views/layouts/_logout_button.html.erb
<% if user_signed_in? %>
  <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "btn btn-success", id: "logout-button" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instagram</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <%= javascript_importmap_tags %>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
  </head>
  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="row">
      <div class="container-fluid">
        <div class="row text-center">
          <div class="col-lg-3 text-center">
            <h4>Instagram</h4>
          </div>
          <div class="col-lg-3"></div>
          <div class="col-lg-3"></div>
          <div class="col-lg-3">
            <div>
              <h4><%= render partial: "layouts/logout_button" %></h4>
              <h4> <%= t('.hello') %> <%= current_user&.username %></h4>
            </div>
            <div>
              <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <%= t('.language_button') %>
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                  <% I18n.available_locales.each do |locale| %>
                    <li>
                      <% if I18n.locale == locale %>
                        <%= tag.span t(locale), class: 'dropdown-item' %>
                      <% else %>
                        <%= link_to t(locale), url_for(locale: locale),
                      class: 'dropdown-item' %>
                      <% end %>
                    </li>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="row text-center">
      <div class="col-lg-2 table-bordered ml-4" id="menu">
        <div class="mt-4">
          <%= link_to t('.home'), root_path %>
        </div>
        <div class="button mt-2"><%= button_to t('.create_button'), new_user_post_path, method: :get %></div>
        <div class="button mt-2"><%= button_to t('.feeds'), feeds_path, method: :get %></div>
        <div class="button mt-2"><%= button_to t('.user_posts'), user_posts_path, method: :get %></div>
        <div></div>
      </div>
      <%= yield %>
      <div class="col-lg-2">
        <div class="container text-center">
        </div>
      </div>
    </div>
  </body>
</html>